language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run ci:test
  - npm run ci:lint
  - npm run ci:build:github:page

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  chrome: stable

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: "github-page"
  on:
    branch: next
